name: Deploy 1 tier app ITI
run-name: Deploy Feed Back by ${{ github.actor }} and Event is ${{ github.event_name }}

on: 
  push:
    branches:
      - master
jobs:
 CI-1tier-app:
  runs-on: ubuntu-latest
  steps:
  - name: clone repo
    uses: actions/checkout@v4
  - name: Install Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.9' 

  - name: Install Requirements
    working-directory: ./
    run: |
      python -m pip install --upgrade pip
       pip install -r requirements.txt

  - name: Test Linting 
    working-directory: ./
    run: |
      pip install flake8
      flake8 .
    continue-on-error: true

  - name: Testing 
    run: | 
     pip install pytest
     PYTHONPATH=./ pytest
    continue-on-error: true
  - name: docker login 
    uses: docker/login-action@v3
    with:
      username: ${{ vars.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
  - name: Build and push
    uses: docker/build-push-action@v6
    with:
        context: .
        push: true
        tags: mohamedezzat1/iti-actions:${{ github.run_number }}